jobs:
  - name: rest-api
    plan:
      - get: docker-image
        trigger: true
      - params:
          kubectl: cluster-info
          app_name: rest-api
          image: ((docker_repo))
          namespace: default
        put: knative-serving

resource_types:
  - name: knative-serving
    source:
      repository: aptomisvc/concourse-knative-serving-resource
      tag: latest
    type: docker-image

resources:
  - name: knative-serving
    source:
      kubeconfig: ((kubeconfig))
    type: knative-serving
  - name: docker-image
    source:
      repository: ((docker_repo))
      tag: latest
    type: docker-image
