---

resources:

- name: aptomi-concourse-pipelines
  type: git
  source:
    uri: https://github.com/Aptomi/concourse-pipelines.git

jobs:

- name: test
  plan:
  - get: aptomi-concourse-pipelines

  - task: external-task
    file: aptomi-concourse-pipelines/task-params-github-issue-454/task.yaml
    vars:
      image: ((image))
